services:
  deployment:
    build:
      context: .
    ports:
      - "80:443"
    image: sel
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: sel  # Assuming you tagged it with 'sel' as per your command
#    command: uvicorn main:app --host 0.0.0.0 --port 443
#    ports:
#      - "8000:443"
#    restart: unless-stopped
#    environment:
#      - ENV_VAR_NAME=value
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:443/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5